services:
  admin-hl:
    build:
      context: ..
      dockerfile: scripts/Dockerfile
    image: admin-hl:latest
    container_name: admin-hl
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
